//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aerolinea.Models.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ciudad
    {
        public Ciudad()
        {
            this.Destino = new HashSet<Destino>();
            this.Origen = new HashSet<Origen>();
        }
    
        public int Id { get; set; }
        public string Nombre { get; set; }
        public int IdAeropuerto { get; set; }
    
        public virtual Aeropuerto Aeropuerto { get; set; }
        public virtual ICollection<Destino> Destino { get; set; }
        public virtual ICollection<Origen> Origen { get; set; }
    }
}
