//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aerolinea.Models.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cliente
    {
        public Cliente()
        {
            this.Pasaje = new HashSet<Pasaje>();
        }
    
        public int Id { get; set; }
        public string Rut { get; set; }
        public string Nombre { get; set; }
        public int Edad { get; set; }
        public int Telefono { get; set; }
        public string Email { get; set; }
    
        public virtual ICollection<Pasaje> Pasaje { get; set; }
    }
}
