//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aerolinea.Models.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Destino
    {
        public Destino()
        {
            this.Itinerario = new HashSet<Itinerario>();
        }
    
        public int Id { get; set; }
        public System.DateTime FechaLlegada { get; set; }
        public System.DateTime HoraLlegada { get; set; }
        public int IdCiudad { get; set; }
    
        public virtual Ciudad Ciudad { get; set; }
        public virtual ICollection<Itinerario> Itinerario { get; set; }
    }
}
