//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aerolinea.Models.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pasaje
    {
        public int Id { get; set; }
        public string Clase { get; set; }
        public string Asiento { get; set; }
        public int Valor { get; set; }
        public int IdCliente { get; set; }
        public int IdVuelo { get; set; }
    
        public virtual Cliente Cliente { get; set; }
        public virtual Vuelo Vuelo { get; set; }
    }
}
