//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aerolinea.Models.Domain.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Aeropuerto
    {
        public Aeropuerto()
        {
            this.Ciudad = new HashSet<Ciudad>();
        }
    
        public int Id { get; set; }
        public string Nombre { get; set; }
    
        public virtual ICollection<Ciudad> Ciudad { get; set; }
    }
}
