//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aerolinea.Models.Domain.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Itinerario
    {
        public Itinerario()
        {
            this.Vuelo = new HashSet<Vuelo>();
        }
    
        public int Id { get; set; }
        public int IdOrigen { get; set; }
        public int IdDestino { get; set; }
    
        public virtual Destino Destino { get; set; }
        public virtual Origen Origen { get; set; }
        public virtual ICollection<Vuelo> Vuelo { get; set; }
    }
}
