//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aerolinea.Models.Domain.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vuelo
    {
        public Vuelo()
        {
            this.Pasaje = new HashSet<Pasaje>();
        }
    
        public int Id { get; set; }
        public int Capacidad { get; set; }
        public string ModeloAvion { get; set; }
        public string NumeroVuelo { get; set; }
        public int IdEmpresa { get; set; }
        public int IdItinerario { get; set; }
    
        public virtual Empresa Empresa { get; set; }
        public virtual Itinerario Itinerario { get; set; }
        public virtual ICollection<Pasaje> Pasaje { get; set; }
    }
}
